Repository upfluence/ember-upf-utils, pull requests merged in 2018-06, with the labels that each got.

#126 Influencer line
  addon/components/display-field/component.js
  addon/components/display-field/template.hbs
  addon/components/influencer/er-gauge-list/component.js
  addon/components/influencer/er-gauge-list/er-gauge/component.js
  addon/components/influencer/er-gauge-list/er-gauge/template.hbs
  addon/components/influencer/er-gauge-list/template.hbs
  addon/components/influencer/medias-list/component.js
  addon/components/influencer/medias-list/template.hbs
  addon/components/influencer/profile-description/component.js
  addon/components/influencer/profile-description/template.hbs
  addon/components/table-fluid/row-link/template.hbs
  addon/components/table-fluid/template.hbs
  app/components/influencer/er-gauge-list/component.js
  app/components/influencer/er-gauge-list/er-gauge/component.js
  app/styles/colors.less
  app/styles/components/influencer/er-gauge-list/er-gauge/styles.less
  app/styles/components/influencer/medias-list/styles.less
  app/styles/components/influencer/profile-description/styles.less
  app/styles/helpers/colors.less
  app/styles/table-fluid/styles.less
  app/styles/upf-utils.less
  app/styles/upf-variables.less
  tests/integration/components/influencer/er-gauge-list/component-test.js
  tests/integration/components/influencer/er-gauge-list/er-gauge/component-test.js
Labels: reviewed/ready-to-merge

#130 Handle back routes with query params in access panel
  addon/mixins/has-access-panel.js
Labels: reviewed/ready-to-merge

#131 stop revalidation if table-fluid is being destroyed
  addon/components/table-fluid/component.js
Labels: reviewed/needs-work

#133 Fetch and display notifications
  addon/activity-notifier/service.js
  addon/configuration.js
  addon/mixins/activity-runner.js
  app/activity-notifier/service.js
  app/styles/components/activity-notifier.less
  app/styles/upf-utils.less
  tests/unit/activity-notifier/service-test.js
  tests/unit/mixins/activity-runner-test.js
Labels: reviewed/needs-review

#132 Line v2
  addon/components/influencer/profile-description/component.js
  addon/components/influencer/profile-description/template.hbs
  addon/components/table-fluid/template.hbs
  app/styles/components/influencer/medias-list/styles.less
  app/styles/components/influencer/profile-description/styles.less
  app/styles/components/split-overlay-area/styles.less
  app/styles/table-fluid/styles.less
  app/styles/upf-variables.less
Labels: reviewed/ready-to-merge

#134 Remove useless meta
  addon/components/influencer/medias-list/component.js
  addon/components/influencer/profile-description/template.hbs
Labels: reviewed/ready-to-merge

#135 Direct notification
  addon/activity-notifier/service.js
Labels: reviewed/needs-review

#136 Display publishr notifications
  addon/activity-notifier/service.js
Labels: reviewed/ready-to-merge
