Repository upfluence/ember-upf-utils, pull requests merged in 2021-06, with the labels that each got.

#281 Display message when limit is exceeded in infinity scroll
  addon/components/table-fluid/component.js
  translations/en-us.yaml
Labels: reviewed/ready-to-merge

#282 draft-display: Ensure that draft images doesn't overflow the container
  app/styles/components/publishr/draft-display.less
Labels: reviewed/ready-to-merge

#283 *: add tooltips on the left-menu component
  addon/components/layout/left-menu/template.hbs
  translations/en-us.yaml
Labels: enhancement, reviewed/ready-to-merge

#284 Use new tags
  .ember-cli
  addon/components/influencer/profile-description/component.js
  addon/components/influencer/profile-description/template.hbs
  app/styles/components/influencer/profile-description/styles.less
  index.js
  translations/en-us.yaml
Labels: reviewed/needs-review

#285 Fix LDA tag not loading correctly
  addon/components/influencer/profile-description/component.js
  addon/components/influencer/profile-description/template.hbs
Labels: reviewed/ready-to-merge
