Repository upfluence/ember-upf-utils, pull requests merged in 2022-05, with the labels that each got.

#326 swap block-slots package for named-blocks pollyfill
  addon/components/table-fluid/component.js
  addon/components/table-fluid/template.hbs
  package.json
  yarn.lock
Labels: reviewed/ready-to-merge

#327 Add activity service
  addon/services/activity-watcher.ts
  app/services/activity-watcher.js
  package.json
  tests/unit/services/activity-watcher-test.ts
  yarn.lock
Labels: enhancement, reviewed/ready-to-merge

#328 Use new toast service for notifications
  addon/services/activity-watcher.ts
  tests/unit/services/activity-watcher-test.ts
  yarn.lock
Labels: reviewed/needs-review
